# Generated by Django 5.1.2 on 2024-11-08 08:40

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaboraterequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Request', 'verbose_name_plural': 'Contact Requests'},
        ),
        migrations.AddField(
            model_name='collaboraterequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaboraterequest',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collaboraterequest',
            name='message',
            field=models.TextField(help_text='Maximum 1000 characters', max_length=1000),
        ),
        migrations.AlterField(
            model_name='collaboraterequest',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, and hyphens', regex='^[A-Za-z\\s-]*$')]),
        ),
    ]
