# Generated by Django 5.1.2 on 2024-10-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('category', models.CharField(choices=[('earrings', 'Earrings'), ('necklaces', 'Necklaces'), ('bracelets', 'Bracelets')], max_length=20)),
                ('material', models.CharField(choices=[('silver', 'Silver'), ('brass', 'Brass')], max_length=20)),
                ('gemstone_type', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/images/')),
            ],
        ),
    ]
